services:
  backend:
    build: ../backend
    command: npm run dev
    volumes:
      - ../backend:/workspace/backend
    networks:
      - devnet
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/quleepdb
      - ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ../frontend
    command: npm start
    volumes:
      - ../frontend:/workspace/frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devnet

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quleepdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  db-data:

networks:
  devnet:
